---
abstract: 'A mock class for Cache::Memcached'
author:
  - 'Cosimo Streppone <cosimo@opera.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 3.101520, CPAN::Meta::Converter version 2.101461'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cache-Memcached-Mock
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Cache-Memcached-Mock
  repository: git://github.com/operasoftware/perl5-cache-memcached-mock.git
version: 0.06
